baseURL = 'https://iris.informatik.uni-bremen.de/student'
languageCode = 'en-us'
title = 'IntEL4CoRo'
theme = 'github-style'


[params]
  author = "Jörn Syrbe"
  description = "Student"
  github = "IntEL4CoRo"
  email = "syrbe@uni-bremen.de"
  lastmod = true
  userStatusEmoji = "🙂"
  favicon = "https://ai.uni-bremen.de/lib/tpl/agkitpl/images/ai_small.png"
  location = "Bremen, Germany"
  enableGitalk = false

[[params.links]]
  title = "Institute for Artificial Intelligence"
  href = "https://ai.uni-bremen.de/"
  icon = "https://ai.uni-bremen.de/lib/tpl/agkitpl/images/ai_small.png"
[[params.links]]
  title = "Uni-Bremen"
  href = "https://www.uni-bremen.de/"
  icon = "https://www.duweisstwarum.de/wp-content/uploads/2022/04/UHB-Uni-Bremen-duweisstwarum-01.png"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files